CREATE TABLE whois(
  whois_id BIGSERIAL PRIMARY KEY,
  domain VARCHAR NOT NULL,
  ip VARCHAR NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE NULL
)