CREATE TABLE logs(
  id BIGSERIAL PRIMARY KEY,
  log_action VARCHAR NOT NULL,
  ip VARCHAR NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT logs_user_id_fkey FOREIGN KEY (user_id)
      REFERENCES users (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)